#!/bin/sh
#
# Copyright (c) 2016-2020 Johnothan King
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# The version of the script
SCRIPTVER='v1.2.5'

# Print and read
eread() {
	echo "$1"
	read "$2"
}

echo  "3dsmicrosd $SCRIPTVER"
echo  ""
eread "Enter the username used for microSD management on the New 3DS..." n3dsusr
eread "Enter the name the New 3DS uses for microSD management..." n3dsname
eread "Enter the local IP address of the New 3DS..." n3dsip
eread "Where would you like to mount your microSD card? (e.g. /mnt)..." n3dsmnt

# Mount the microSD card
sudo mkdir -p "$n3dsmnt"
sudo mount -t cifs "//$n3dsname/microSD" "$n3dsmnt" -o "user=$n3dsusr,ip=$n3dsip,servern=$n3dsname,uid=`sudo -u \`whoami\` id -u`,gid=`sudo -u \`whoami\` id -g`,nounix,vers=1.0"
echo ""

# Check to see if the mount was successful
if [ -d "$n3dsmnt/Nintendo 3DS" ]
then
	# Allow the user to use a shell for transferring files
	echo "The microSD card is now mounted at $n3dsmnt"
	echo "Which shell would you like to use (e.g. /bin/bash)? This will allow you to transfer your files between your PC and 3DS..."
	while true; do
		read n3dsshell
		if [ -x "$n3dsshell" ]; then
			$n3dsshell
			break
		else
			echo "Please select a valid shell..."
		fi
	done

	# Unmount the microSD card when done
	sync
	sudo umount -R "$n3dsmnt"
	exit 0
else # If it failed
	echo 'The microSD card failed to mount!'
	exit 1
fi
