#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2016 Johnothan King
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Version of the script
export SCRIPTVER=0.8.3

# Function to verify if the specified shell exists
verifyshell()
{
    read n3dsshell
    command -v "$n3dsshell" > /dev/null
    if [ $? = 1 ]
    then
        echo "The specified shell doesn't exist. Please specify a valid shell:"
        verifyshell
    else
        "$n3dsshell"
    fi
}

echo "3dsmicrosd version $SCRIPTVER"
echo -e "\nEnter the username used for microSD management on the New 3DS:"
read n3dsusr
echo -e "\nEnter the name the New 3DS uses for microSD management:"
read n3dsname
echo -e "\nEnter the New 3DS's local ip address:"
read n3dsip
echo -e "\nWhere would you like to mount your microSD card: ?"
read n3dsmnt

# Mount the microSD card
sudo mkdir -p "$n3dsmnt"
sudo mount -t cifs //"$n3dsname"/microSD "$n3dsmnt" -o user="$n3dsusr",ip=$n3dsip,servern="$n3dsname",uid=$(sudo -u $(whoami) id -u),gid=$(sudo -u $(whoami) id -g),nounix

# Check to see if the mount was successful
if [ -e "$n3dsmnt/Nintendo 3DS" ]
then
    echo -e "\nThe New 3DS's microSD card is mounted at $n3dsmnt\n"

    # Allow the user to enter a shell for transfering files
    echo -e "Input your favorite shell now (ex. zsh or fish) to use it.\nTo exit the shell or this prompt, enter exit at any time."
    verifyshell

    # Unmount the microSD card when done
    sync
    sudo umount -R "$n3dsmnt"
    exit 0
else # If it failed
    echo -e "\nThe microSD card failed to mount!"
    exit 1
fi
